### ISSUE TITLE
Allow multiline for react/jsx-curly-spacing

### ISSUE THREAD

**Issue by drudolf** [zattoo/eslint-config#7]
I would like to change the jsx-curly-spacing rule to

```
"react/jsx-curly-spacing": ["error", {
    "when": "never",
         "allowMultiline": true
    }]
}
```

so its possible to write something like

```
top={
    <div>
        text
    </div>
}
```

**Comment by godban** [comment]
Not sure. Passing jsx objects instead of function/string looks like antipattern to me

**Comment by godban** [comment]
I would rather go with `top={text}` or `top={Component}`

**Comment by drudolf** [comment]
Yeah, can also define these parts before and store them in a variable. Perhaps its best to refactor the parts I directly injected JSX this way completey and come up wiht a better solution. Same day.
